import { Exercise, Workout } from '../types';

export const SEED_WORKOUTS: Workout[] = [
  { id: 1, name: 'Push', description: 'Pectoraux, Épaules, Triceps + Finisher Développé couché' },
  { id: 2, name: 'Pull', description: 'Grand dorsal, Épaisseur du dos, Biceps + Finisher Deadlift' },
  { id: 3, name: 'Legs', description: 'Quadriceps, Ischios, Mollets + Finisher Squat' },
];

export const SEED_EXERCISES: Exercise[] = [
  // --- PUSH ---
  {
    id: 1,
    workoutId: 1,
    name: 'HS Iso-Lateral Incline Press',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 1,
    defaultTargetReps: 8,
    defaultStartingWeight: 40,
  },
  {
    id: 2,
    workoutId: 1,
    name: 'HS Iso-Lateral Shoulder Press',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 2,
    defaultTargetReps: 8,
    defaultStartingWeight: 30,
  },
  {
    id: 3,
    workoutId: 1,
    name: 'HS Plate-Loaded Seated Dip',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 3,
    defaultTargetReps: 8,
    defaultStartingWeight: 40,
  },
  {
    id: 4,
    workoutId: 1,
    name: 'Développé couché barre libre (Finisher)',
    category: 'FREE_WEIGHT',
    minIncrement: 2.5,
    baseWeight: 20, // Barre olympique = 20 kg
    orderIndex: 4,
    defaultTargetReps: 6,
    defaultStartingWeight: 60,
  },

  // --- PULL ---
  {
    id: 5,
    workoutId: 2,
    name: 'HS Iso-Lateral Front Lat Pulldown',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 1,
    defaultTargetReps: 8,
    defaultStartingWeight: 45,
  },
  {
    id: 6,
    workoutId: 2,
    name: 'HS Iso-Lateral High Row / D.Y. Row',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 2,
    defaultTargetReps: 8,
    defaultStartingWeight: 45,
  },
  {
    id: 7,
    workoutId: 2,
    name: 'HS Plate-Loaded Seated Biceps',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 3,
    defaultTargetReps: 8,
    defaultStartingWeight: 25,
  },
  {
    id: 8,
    workoutId: 2,
    name: 'Deadlift Soulevé de terre (Finisher)',
    category: 'FREE_WEIGHT',
    minIncrement: 2.5,
    baseWeight: 20, // Barre olympique = 20 kg
    orderIndex: 4,
    defaultTargetReps: 5,
    defaultStartingWeight: 80,
  },

  // --- LEGS ---
  {
    id: 9,
    workoutId: 3,
    name: 'HS Plate-Loaded Linear Leg Press',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 1,
    defaultTargetReps: 8,
    defaultStartingWeight: 100,
  },
  {
    id: 10,
    workoutId: 3,
    name: 'HS Iso-Lateral Leg Extension',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 2,
    defaultTargetReps: 8,
    defaultStartingWeight: 40,
  },
  {
    id: 11,
    workoutId: 3,
    name: 'HS Iso-Lateral Leg Curl',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 3,
    defaultTargetReps: 8,
    defaultStartingWeight: 35,
  },
  {
    id: 12,
    workoutId: 3,
    name: 'HS Plate-Loaded Seated Calf Raise',
    category: 'HAMMER_STRENGTH',
    minIncrement: 2.5,
    baseWeight: 0,
    orderIndex: 4,
    defaultTargetReps: 10,
    defaultStartingWeight: 30,
  },
  {
    id: 13,
    workoutId: 3,
    name: 'Squat barre libre (Finisher)',
    category: 'FREE_WEIGHT',
    minIncrement: 2.5,
    baseWeight: 20, // Barre olympique = 20 kg
    orderIndex: 5,
    defaultTargetReps: 6,
    defaultStartingWeight: 70,
  },
];
